version: 2
updates:
  - package-ecosystem: npm
    directory: /english-ai/apps/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /english-ai/apps/mobile
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
