import pg from "pg";
import type { SkillScores } from "./progress-engine.js";
import type { LearnerMemory } from "./memory.js";
import type { Mistake } from "./store.js";
const { Pool } = pg;
const pool = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_SSL === "false" ? false : { rejectUnauthorized: false } }) : null;
export type StoredProfile = { level: string; scores: SkillScores };
export function databaseEnabled() { return Boolean(pool); }
async function ensureUser(externalUserId: string) { if (!pool) return null; const r = await pool.query(`INSERT INTO users (external_id,email) VALUES ($1,$2) ON CONFLICT (external_id) DO UPDATE SET updated_at=now() RETURNING id`, [externalUserId,`${externalUserId}@studyos.local`]); return r.rows[0].id as string; }
export async function loadProfile(id:string):Promise<StoredProfile|null>{if(!pool)return null;const r=await pool.query(`SELECT cefr_level,speaking_score,listening_score,grammar_score,vocabulary_score,pronunciation_score FROM learning_profiles lp JOIN users u ON u.id=lp.user_id WHERE u.external_id=$1`,[id]);if(!r.rowCount)return null;const x=r.rows[0];return{level:String(x.cefr_level),scores:{speaking:Number(x.speaking_score),listening:Number(x.listening_score),grammar:Number(x.grammar_score),vocabulary:Number(x.vocabulary_score),pronunciation:Number(x.pronunciation_score)}}}
export async function saveProfile(id:string,p:StoredProfile){if(!pool)return;const uid=await ensureUser(id);await pool.query(`INSERT INTO learning_profiles(user_id,cefr_level,speaking_score,listening_score,grammar_score,vocabulary_score,pronunciation_score,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()) ON CONFLICT(user_id) DO UPDATE SET cefr_level=EXCLUDED.cefr_level,speaking_score=EXCLUDED.speaking_score,listening_score=EXCLUDED.listening_score,grammar_score=EXCLUDED.grammar_score,vocabulary_score=EXCLUDED.vocabulary_score,pronunciation_score=EXCLUDED.pronunciation_score,updated_at=now()`,[uid,p.level,p.scores.speaking,p.scores.listening,p.scores.grammar,p.scores.vocabulary,p.scores.pronunciation])}
export async function loadMemory(id:string):Promise<LearnerMemory|null>{if(!pool)return null;const uid=await ensureUser(id);const r=await pool.query(`SELECT goal,interests,preferred_topics,learned_vocabulary,conversation_count,total_turns,last_active_at FROM learner_memory WHERE user_id=$1`,[uid]);if(!r.rowCount)return null;const x=r.rows[0];return{userId:id,interests:x.interests??[],goals:x.goal?[x.goal]:[],vocabulary:x.learned_vocabulary??[],preferredTopics:x.preferred_topics??[],conversationCount:Number(x.conversation_count),totalTurns:Number(x.total_turns),lastActiveAt:new Date(x.last_active_at).toISOString()}}
export async function saveMemory(m:LearnerMemory){if(!pool)return;const uid=await ensureUser(m.userId);await pool.query(`INSERT INTO learner_memory(user_id,goal,interests,preferred_topics,learned_vocabulary,conversation_count,total_turns,last_active_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,now()) ON CONFLICT(user_id) DO UPDATE SET goal=EXCLUDED.goal,interests=EXCLUDED.interests,preferred_topics=EXCLUDED.preferred_topics,learned_vocabulary=EXCLUDED.learned_vocabulary,conversation_count=EXCLUDED.conversation_count,total_turns=EXCLUDED.total_turns,last_active_at=EXCLUDED.last_active_at,updated_at=now()`,[uid,m.goals.at(-1)??null,m.interests,m.preferredTopics,m.vocabulary,m.conversationCount,m.totalTurns,m.lastActiveAt])}
export async function loadMistakes(id:string):Promise<Mistake[]>{if(!pool)return[];const uid=await ensureUser(id);const r=await pool.query(`SELECT id,category,source,original_text,corrected_text,count,resolved,last_seen_at FROM mistakes WHERE user_id=$1 AND resolved=false ORDER BY count DESC,last_seen_at DESC`,[uid]);return r.rows.map(x=>({id:String(x.id),userId:id,category:String(x.category),source:String(x.source),originalText:x.original_text??undefined,correctedText:x.corrected_text??undefined,count:Number(x.count),resolved:Boolean(x.resolved),lastSeenAt:new Date(x.last_seen_at).toISOString()}))}
export async function saveMistake(input:Omit<Mistake,"id"|"count"|"resolved"|"lastSeenAt">):Promise<Mistake>{if(!pool)throw new Error("database disabled");const uid=await ensureUser(input.userId);const e=await pool.query(`SELECT id FROM mistakes WHERE user_id=$1 AND category=$2 AND original_text IS NOT DISTINCT FROM $3 AND resolved=false LIMIT 1`,[uid,input.category,input.originalText??null]);const r=e.rowCount?await pool.query(`UPDATE mistakes SET count=count+1,last_seen_at=now(),corrected_text=$2 WHERE id=$1 RETURNING id,count,last_seen_at`,[e.rows[0].id,input.correctedText??null]):await pool.query(`INSERT INTO mistakes(user_id,category,source,original_text,corrected_text) VALUES($1,$2,$3,$4,$5) RETURNING id,count,last_seen_at,resolved`,[uid,input.category,input.source,input.originalText??null,input.correctedText??null]);const x=r.rows[0];return{...input,id:String(x.id),count:Number(x.count),resolved:Boolean(x.resolved??false),lastSeenAt:new Date(x.last_seen_at).toISOString()}}
export async function resolveMistakeDb(id:string,mistakeId:string):Promise<Mistake|null>{if(!pool)return null;const uid=await ensureUser(id);const r=await pool.query(`UPDATE mistakes SET resolved=true WHERE id=$1 AND user_id=$2 RETURNING id,category,source,original_text,corrected_text,count,resolved,last_seen_at`,[mistakeId,uid]);if(!r.rowCount)return null;const x=r.rows[0];return{id:String(x.id),userId:id,category:String(x.category),source:String(x.source),originalText:x.original_text??undefined,correctedText:x.corrected_text??undefined,count:Number(x.count),resolved:true,lastSeenAt:new Date(x.last_seen_at).toISOString()}}
export async function createConversation(id:string,topic:string,level:string){if(!pool)return null;const uid=await ensureUser(id);const r=await pool.query(`INSERT INTO conversations(user_id,topic,cefr_level) VALUES($1,$2,$3) RETURNING id`,[uid,topic,level]);return String(r.rows[0].id)}
export async function getActiveConversation(id:string){if(!pool)return null;const uid=await ensureUser(id);const r=await pool.query(`SELECT id FROM conversations WHERE user_id=$1 AND ended_at IS NULL ORDER BY started_at DESC LIMIT 1`,[uid]);return r.rowCount?String(r.rows[0].id):null}
export async function saveConversationMessage(conversationId:string,role:"user"|"assistant"|"system",content:string,metadata:Record<string,unknown>={}){if(!pool)return;await pool.query(`INSERT INTO conversation_messages(conversation_id,role,content,metadata) VALUES($1,$2,$3,$4)`,[conversationId,role,content,JSON.stringify(metadata)])}
export async function recordLearningEvent(id:string,skill:string,performance:number,source:string,metadata:Record<string,unknown>={}){if(!pool)return;const uid=await ensureUser(id);await pool.query(`INSERT INTO learning_events(user_id,skill,performance,source,metadata) VALUES($1,$2,$3,$4,$5)`,[uid,skill,performance,source,JSON.stringify(metadata)])}
export async function closeDatabase(){if(pool)await pool.end()}
