import express from "express";
import multer from "multer";
import { buildDailyPlan, type LearningProfile } from "./learning-engine.js";
import { buildAdaptiveLesson, type AdaptiveInput, type Skill } from "./adaptive-engine.js";
import { generateTutorReply } from "./ai-tutor.js";
import { getLearnerMemory, recordConversation, recordLearnerTurn, updateLearnerMemory } from "./memory.js";
import { listOpenMistakes, recordMistake, resolveMistake } from "./store.js";
import { synthesizeSpeech, transcribeAudio } from "./speech.js";
import { updateSkillScores, progressSnapshot, type SkillScores } from "./progress-engine.js";
import { databaseEnabled, loadProfile, saveProfile as persistProfile, createConversation, getActiveConversation, saveConversationMessage, recordLearningEvent, closeDatabase } from "./database.js";
import { requireAuth, requestUserId, type AuthenticatedRequest } from "./auth.js";
import { validateEnvironment } from "./env.js";
import { rateLimit, aiRateLimit, voiceRateLimit, realtimeRateLimit } from "./rate-limit.js";

validateEnvironment();
const app = express();
const port = Number(process.env.PORT ?? 4000);
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 15 * 1024 * 1024, files: 1 } });
app.disable("x-powered-by");
app.set("trust proxy", process.env.TRUST_PROXY === "true" ? 1 : 0);
app.use((_req, res, next) => {
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("X-Frame-Options", "DENY");
  res.setHeader("Referrer-Policy", "no-referrer");
  res.setHeader("Permissions-Policy", "microphone=(), camera=(), geolocation=()");
  next();
});
app.use(express.json({ limit: "2mb", strict: true }));
app.use(rateLimit);
app.use("/api/v1", requireAuth);
const defaultScores: SkillScores = { speaking: 28, listening: 35, grammar: 36, vocabulary: 42, pronunciation: 30 };
const profiles = new Map<string, { level: string; scores: SkillScores }>();
const routeParam = (value: string | string[] | undefined): string => Array.isArray(value) ? String(value[0] ?? "") : String(value ?? "");
const boundedString = (value: unknown, max: number): string | undefined => {
  if (value === undefined || value === null) return undefined;
  const text = String(value).trim();
  return text ? text.slice(0, max) : undefined;
};
async function getProfile(userId: string) { const cached=profiles.get(userId); if(cached)return cached; const stored=await loadProfile(userId); const profile=stored??{level:"A1",scores:{...defaultScores}}; profiles.set(userId,profile); return profile; }
async function saveProfile(userId:string,level:string,scores:SkillScores){const profile={level,scores};profiles.set(userId,profile);await persistProfile(userId,profile);return profile;}
app.get("/health",(_req,res)=>res.json({ok:true,service:"studyos-english-api",aiEnabled:Boolean(process.env.OPENAI_API_KEY),voiceEnabled:Boolean(process.env.OPENAI_API_KEY),realtimeEnabled:Boolean(process.env.OPENAI_API_KEY),adaptiveEngine:true,progressEngine:true,database:databaseEnabled(),authRequired:process.env.AUTH_REQUIRED === "true"}));
app.get("/api/v1/lessons/daily",(req,res)=>{const level=String(req.query.level??"A1").toUpperCase();const minutes=Math.max(5,Math.min(60,Number(req.query.minutes??10)));res.json({plan:buildDailyPlan({cefrLevel:level,...defaultScores},minutes)});});
app.get("/api/v1/users/:userId/lesson/today",async(req:AuthenticatedRequest,res)=>{const userId=requestUserId(req,routeParam(req.params.userId));const profile=await getProfile(userId);const dailyMinutes=Math.max(5,Math.min(60,Number(req.query.minutes??10)));const memory=await getLearnerMemory(userId);const mistakes=await listOpenMistakes(userId);const input:AdaptiveInput={level:profile.level,goal:memory.goals.at(-1),dailyMinutes,scores:profile.scores,mistakes,interests:memory.interests};res.json({lesson:buildAdaptiveLesson(input),progress:progressSnapshot(profile.scores,profile.level),memory,mistakes});});
app.get("/api/v1/users/:userId/progress",async(req:AuthenticatedRequest,res)=>{const profile=await getProfile(requestUserId(req,routeParam(req.params.userId)));res.json({progress:progressSnapshot(profile.scores,profile.level)});});
app.post("/api/v1/users/:userId/progress/score",async(req:AuthenticatedRequest,res)=>{const userId=requestUserId(req,routeParam(req.params.userId));const profile=await getProfile(userId);const skill=String(req.body?.skill??"speaking") as Skill;if(!(skill in profile.scores))return res.status(400).json({error:"invalid skill"});const performance=Number(req.body?.performance??0);if(!Number.isFinite(performance)||performance<0||performance>100)return res.status(400).json({error:"performance must be between 0 and 100"});const scores=updateSkillScores(profile.scores,skill,performance);const next=await saveProfile(userId,progressSnapshot(scores,profile.level).cefrLevel,scores);await recordLearningEvent(userId,skill,performance,"manual");return res.json({progress:progressSnapshot(next.scores,next.level)});});
app.post("/api/v1/placement/submit",async(req:AuthenticatedRequest,res)=>{const score=Math.max(0,Math.min(100,Number(req.body?.score??0)));if(!Number.isFinite(score))return res.status(400).json({error:"score must be a number"});const level=score>=80?"B2":score>=60?"B1":score>=40?"A2":"A1";const userId=requestUserId(req,req.body?.userId);await saveProfile(userId,level,{...defaultScores,speaking:score,grammar:score,vocabulary:score});res.json({score,level,nextStep:"Start your personalized daily lesson."});});
app.get("/api/v1/users/:userId/memory",async(req:AuthenticatedRequest,res)=>res.json({memory:await getLearnerMemory(requestUserId(req,routeParam(req.params.userId)))}));
app.patch("/api/v1/users/:userId/memory",async(req:AuthenticatedRequest,res)=>res.json({memory:await updateLearnerMemory(requestUserId(req,routeParam(req.params.userId)),req.body??{})}));
app.get("/api/v1/users/:userId/mistakes",async(req:AuthenticatedRequest,res)=>res.json({mistakes:await listOpenMistakes(requestUserId(req,routeParam(req.params.userId)))}));
app.post("/api/v1/users/:userId/mistakes",async(req:AuthenticatedRequest,res)=>res.status(201).json({mistake:await recordMistake({userId:requestUserId(req,routeParam(req.params.userId)),category:boundedString(req.body?.category,100)??"grammar",source:boundedString(req.body?.source,100)??"conversation",originalText:boundedString(req.body?.originalText,4000),correctedText:boundedString(req.body?.correctedText,4000)})}));
app.post("/api/v1/users/:userId/mistakes/:id/resolve",async(req:AuthenticatedRequest,res)=>{const item=await resolveMistake(requestUserId(req,routeParam(req.params.userId)),routeParam(req.params.id));if(!item)return res.status(404).json({error:"Mistake not found"});return res.json({mistake:item});});
async function handleTutorTurn(userId:string,message:string,level:string,goal?:string){const memory=await getLearnerMemory(userId);await recordLearnerTurn(userId);const mistakes=await listOpenMistakes(userId);const ai=await generateTutorReply(message,{level,goal,mistakes,memory});if(ai){const correction=ai.correction?String(ai.correction).slice(0,4000):null;if(correction)await recordMistake({userId,category:String(ai.category??"grammar").slice(0,100),source:"conversation",originalText:message,correctedText:correction});return{reply:String(ai.reply??"Tell me more.").slice(0,4000),correction,category:String(ai.category??"speaking").slice(0,100),score:Number(ai.score??85),reviewQueued:Boolean(correction),provider:"openai" as const};}const correction=/yesterday.*\bgo\b|\bi go\b/i.test(message)?"Yesterday, I went to...":null;if(correction)await recordMistake({userId,category:"grammar",source:"conversation",originalText:message,correctedText:correction});return{reply:correction?`Good job. A natural correction is: "${correction}". Now try saying the whole sentence.`:"Nice! Tell me a little more about that.",correction,category:correction?"grammar":"speaking",score:correction?78:88,reviewQueued:Boolean(correction),provider:"fallback" as const};}
function skillFromCategory(category:string):Skill{const value=category.toLowerCase();if(value.includes("pronunciation"))return"pronunciation";if(value.includes("vocab"))return"vocabulary";if(value.includes("listen"))return"listening";if(value.includes("speak"))return"speaking";return"grammar";}
async function processTutorResult(userId:string,result:Awaited<ReturnType<typeof handleTutorTurn>>){const profile=await getProfile(userId);const skill=skillFromCategory(result.category);const score=Math.max(0,Math.min(100,result.score));const scores=updateSkillScores(profile.scores,skill,score);const saved=await saveProfile(userId,progressSnapshot(scores,profile.level).cefrLevel,scores);await recordLearningEvent(userId,skill,score,"tutor",{category:result.category,correction:Boolean(result.correction)});return saved;}
async function persistTutorConversation(userId:string,level:string,topic:string,message:string,result:Awaited<ReturnType<typeof handleTutorTurn>>){if(!databaseEnabled())return;let conversationId=await getActiveConversation(userId);let isNew=false;if(!conversationId){conversationId=await createConversation(userId,topic,level);isNew=true;}if(!conversationId)return;await saveConversationMessage(conversationId,"user",message,{level,topic});await saveConversationMessage(conversationId,"assistant",result.reply,{provider:result.provider,correction:result.correction,category:result.category,score:result.score});if(isNew)await recordConversation(userId);}
app.post("/api/v1/conversations",aiRateLimit,async(req:AuthenticatedRequest,res)=>{const message=boundedString(req.body?.message,4000);const userId=requestUserId(req,req.body?.userId);const profile=await getProfile(userId);const level=String(req.body?.level??profile.level).toUpperCase();const goal=boundedString(req.body?.goal,200);const topic=boundedString(req.body?.topic,200)??"general conversation";if(!message)return res.status(400).json({error:"message is required"});try{const result=await handleTutorTurn(userId,message,level,goal);const saved=await processTutorResult(userId,result);await updateLearnerMemory(userId,{goals:goal?[goal]:[],preferredTopics:topic?[topic]:[]});if(databaseEnabled())await persistTutorConversation(userId,level,topic,message,result);else await recordConversation(userId);return res.json({...result,memory:await getLearnerMemory(userId),progress:progressSnapshot(saved.scores,saved.level)});}catch(error){console.error("AI tutor unavailable",error);return res.status(502).json({error:"Tutor AI unavailable"});}});
app.post("/api/v1/speech/transcribe",voiceRateLimit,upload.single("file"),async(req,res)=>{if(!req.file)return res.status(400).json({error:"file is required"});if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:"Voice AI is not configured. Set OPENAI_API_KEY."});try{return res.json({text:await transcribeAudio(req.file,String(req.body?.language??"en").slice(0,10)),provider:"openai"});}catch{return res.status(502).json({error:"Unable to transcribe audio"});}});
app.post("/api/v1/speech/synthesize",voiceRateLimit,async(req,res)=>{const text=boundedString(req.body?.text,5000);if(!text)return res.status(400).json({error:"text is required"});if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:"Voice AI is not configured. Set OPENAI_API_KEY."});try{return res.json({audioBase64:await synthesizeSpeech(text),mimeType:"audio/mpeg",provider:"openai"});}catch{return res.status(502).json({error:"Unable to synthesize speech"});}});
app.post("/api/v1/voice/turn",voiceRateLimit,upload.single("file"),async(req:AuthenticatedRequest,res)=>{if(!req.file)return res.status(400).json({error:"file is required"});if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:"Voice AI is not configured. Set OPENAI_API_KEY."});const userId=requestUserId(req,req.body?.userId);const profile=await getProfile(userId);const level=String(req.body?.level??profile.level).toUpperCase();const goal=boundedString(req.body?.goal,200);try{const transcript=await transcribeAudio(req.file,String(req.body?.language??"en").slice(0,10));const result=await handleTutorTurn(userId,transcript,level,goal);const saved=await processTutorResult(userId,result);if(databaseEnabled())await persistTutorConversation(userId,level,"voice conversation",transcript,result);else await recordConversation(userId);return res.json({transcript,...result,progress:progressSnapshot(saved.scores,saved.level),audioBase64:await synthesizeSpeech(result.reply),mimeType:"audio/mpeg"});}catch{return res.status(502).json({error:"Unable to process voice turn"});}});
app.post("/api/v1/realtime/call",realtimeRateLimit,async(req:AuthenticatedRequest,res)=>{const sdp=boundedString(req.body?.sdp,500_000);const level=String(req.body?.level??"A1").toUpperCase();const goal=boundedString(req.body?.goal,200)??"general conversation";if(!sdp)return res.status(400).json({error:"sdp is required"});const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return res.status(503).json({error:"Realtime AI is not configured. Set OPENAI_API_KEY."});const instructions=["You are StudyOS English AI, a patient personal English tutor.",`Student CEFR level: ${level}.`,`Student goal: ${goal}.`,"Speak mostly in English. Adapt vocabulary and speed to the student's level.","Keep turns short and natural. Correct one important mistake after the student speaks, then continue the conversation.","Never shame the student. Encourage them to repeat corrected sentences when useful."].join(" ");try{const form=new FormData();form.append("sdp",new Blob([sdp],{type:"application/sdp"}),"offer.sdp");form.append("session",JSON.stringify({type:"realtime",model:process.env.OPENAI_REALTIME_MODEL??"gpt-realtime",audio:{input:{turn_detection:{type:"semantic_vad",eagerness:"medium"}},output:{voice:process.env.OPENAI_REALTIME_VOICE??"marin"}},instructions}));const response=await fetch("https://api.openai.com/v1/realtime/calls",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`},body:form});const answer=await response.text();if(!response.ok)return res.status(response.status).type("application/sdp").send(answer);return res.status(201).type("application/sdp").send(answer);}catch{return res.status(502).json({error:"Unable to create realtime call"});}});
app.use((err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => { console.error("Unhandled API error", err); if (res.headersSent) return; return res.status(500).json({ error: "Internal server error" }); });
const server = app.listen(port,()=>console.log(`StudyOS English API listening on port ${port}`));
process.on("SIGTERM", async () => { server.close(); await closeDatabase(); process.exit(0); });
process.on("SIGINT", async () => { server.close(); await closeDatabase(); process.exit(0); });
